repos:
  - repo: git://github.com/dnephin/pre-commit-golang
    rev: master
    hooks:
      - id: go-unit-tests
      - id: go-build
      - id: go-mod-tidy
  - repo: https://git.services.upcloud.com/engineering/tools/golangci-lint
    rev: v1.42.1-3
    hooks:
      - id: golangci-lint
