name: tests

on:
  pull_request:

jobs:
  platform-tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go-version: [1.13.x, 1.14.x, 1.15.x]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run unit tests
        run: make test
      - name: Test build
        run: make build
      - name: Test Runtime
        run: go run cmd/upctl/main.go -h
